### ISSUE TITLE
Missing variables in methods for observed_dict and observed_tree

### ISSUE THREAD

**Issue by m-charlton** [asrp/undoable#2]
The `popitem` method of the `observed_dict` class has a missing variable `default`

```python
def popitem(self):
    key, value = dict.popitem(self)
    self.callback(("__setitem__", key, default), ("popitem",))
    return key, value
``` 

Calling `popitem()` results in the following:

```
Traceback (most recent call last):
  File "undoable.py", line 453, in <module>
    l.popitem()
AttributeError: 'observed_list' object has no attribute 'popitem'
```

Likewise in the `observed_tree` class the `sort` method has a missing variable
`oldlist`

```python
def sort(self, cmpfunc=None):
    list.sort(self, cmpfunc)
    self.callback(("replace", oldlist), ("sort",))
```

I'm willing to write some unit tests.

**Comment by asrp** [comment]
Thanks for reporting this! Some unit tests would be great.

**Comment by m-charlton** [comment]
No worries. Do you have any preference as to the test framework to use? I've experience with
`unittest` but I'm learning to use `pytest` for another project.

Would it be possible to provide a couple of examples with some callables?

**Comment by asrp** [comment]
To be honest, I haven't found a test framework I really like yet so whichever you like best works for me.

> Would it be possible to provide a couple of examples with some callables?

Oh, sure thing. I'm guessing you mean something other than `undoable.printargs` or the ones from `UndoLog`. I usually use callbacks for GUIs that need to keep multiple parts in sync. But let me think of some non-graphical examples.

### Some opinions about testing frameworks

I usually run stuff in the interpreter for testing and manually inspect the results. I'd be nice if I could just mark some of these lines *and their results* from the interpret's history as "correct" and have tests automatically generated for them. (With maybe a few options for what chaging what "equals" means.)

Maybe I'm thinking of something like doctest but with files in a different directory rather than in the code.

I don't think its going to be the case for `undoable`, but the API and function of programs I try to make tend to change a lot and it'd be nice to have a testing framework suited for that (like fast test creation and removal).

**Comment by asrp** [comment]
So here's a simple non-graphical example and a graphical example. They are both pretty contrived.

```
from undoable import observed_list

class AppendCounter:
    def __init__(self, lst):
        lst.callbacks.append(self.callback)
        self.count = 0

    def callback(self, lst, event, *args):
        if event == "append":
            self.count += 1

l = observed_list()
counter = AppendCounter(l)
l.append(1)
l.append(2)
# Should give 2
print counter.count
```

This one uses [uielem](https://github.com/asrp/uielem). The printed list (with "Print") should always match what's in the ListBox.

```
import Tkinter as tk
from uielem import UI, uidict
from undoable import observed_list

class BoxedList(tk.Listbox):
    def __init__(self, *args, **kwargs):
        self._list = kwargs.pop("_list", observed_list())
        self._list.callbacks.append(self.callback)
        tk.Listbox.__init__(self, *args, **kwargs)
        self.redraw()

    def replace(self, newlist):
        self._list.callbacks.remove(self.callback)
        self._list = newlist
        self._list.callbacks.append(self.callback)
        self.redraw()

    def callback(self, _list, event, *args):
        if event == "append":
            value, = args
            self.insert(tk.END, value)
        elif event == "pop":
            index, = args
            if index < 0:
                index = len(self._list) + index + 1
            self.delete(index)
        elif event == "replace":
            self.redraw()
        elif event == "__setitem__":
            index, value = args
            if index < 0:
                index = len(_list) + index
            self.delete(index)
            self.insert(index, _list[index])
            self.see(index)

    def redraw(self):
        self.delete(0, tk.END)
        for item in self._list:
            self.insert(tk.END, item)

    def append(self, item):
        self.insert(tk.END, item)

    def lselection(self):
        return [self._list[index] for index in self.curselection()]

l = observed_list()

def add():
    l.append(len(l))

def pop():
    l.pop()

def print_list():
    print l

root = UI(tk.Tk, title="BoxedList", packside="left", name="root", children=[
    UI(BoxedList, name="boxed", _list=l),
    UI(tk.Frame, packside="top", children=[
        UI(tk.Button, text="Add", command=add),
        UI(tk.Button, text="Pop", command=pop),
        UI(tk.Button, text="Print", command=print_list)])])

root.makeelem()
uidict["root"].mainloop()
```

Tell me if you'd like to see examples of something more specific.
